name: 04_HelloWorld
trigger:
- master
variables:
  azureSubscription: 'Microsoft Azure Sponsorship (82d445a5-0bf3-454a-804b-2fd0286650c2)'
  artifactName: 'HelloWorldWeb'
resources:
  repositories:
  - repository: templatesRepo
    type: git
    name: YamlPipelinesDemo/PipelineTemplates
stages:
- stage: build
  displayName: 'Build the Application'
  jobs:
  - job: CI_Build
    displayName: 'CI build web application'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      buildConfiguration: 'Release'
      unitTestProjects: '**/*Unit.Tests.csproj'
    steps:
    - template: pipeline/buildversioning.yml
    - template: pipeline/build-and-package-web.yml
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: '$(artifactName)'
      displayName: 'Create pipeline artifact for web app'